### ISSUE TITLE
Structure of Request URL

### ISSUE THREAD

**Issue by JoshFialkoff** [Tinkertanker/YOURLS-Slack#3]
Hi,
Can you please post a sample request url? I am getting a 403 status, which I guess is because my url structure is wrong or missing information.
Thanks!
Josh

**Comment by jamesrchen** [comment]
Could you elaborate? Request URL to where?

**Comment by JoshFialkoff** [comment]
Thanks for your help, @unknownguy2002. Here is the file contents.
Please let me know what you recommend.
Thanks again!
Josh
![config json - cPanel File Manager v3 2019-08-13 11-39-49](https://user-images.githubusercontent.com/3923170/62955584-4d9c4180-bdbf-11e9-9ed1-c9d0b8ef68fc.png)

Here is a video showing the error I get in Slack:

https://www.dropbox.com/s/vau3hbkvm4j6geq/yourls%20slack%20error%20screencast%202019-08-13%2011-44-02.mp4?dl=0
